LPGadmin/urls.py
from django.contrib import admin
from django.urls import path, include
# import cylinders
urlpatterns = [
    path('admin/', admin.site.urls),
    path('cylinders/', include('cylinders.urls')),
]

cylinders/urls.py
from . import views
from django.urls import path


app_name = 'cylinders'
urlpatterns = [
    path('', views.index, name='index'),
    path('page1_gp/', views.page1_gp, name='page1_gp'),
    path('addGp/', views.addGp, name='addGp'),
    
    path('gp_code/<str:gp_code>', views.lookupBygp, name='lookupBygp'),
]

cylinders/models.py
from django.db import models

# Create your models here.
class Gp(models.Model):
    jf_code = models.CharField(max_length=32, default='000000', verbose_name='阀门编号')
    gp_code = models.CharField(max_length=32, default='000000', verbose_name='钢瓶编号')
    zn_code = models.CharField(max_length=32, default='WR23-', verbose_name='站内编号')
    sc_date = models.DateField(verbose_name='生产日期')
    jc_date = models.DateField(verbose_name='检测日期')
    manufacturer = models.CharField(max_length=100, default='宣城市百纳压力容器制造有限公司', verbose_name='制造厂商')
    specification = models.CharField(max_length=32, default='YSP35.5', verbose_name='规格')
    company = models.CharField(max_length=100, default='青山液化气站', verbose_name='充装单位')
    xj_date = models.DateField(verbose_name='下次检测日期')
    bf_date = models.DateField(verbose_name='报废日期')
    remark = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = '钢瓶表'
    # 给模型增加__str__()方法是很重要的，这不仅仅能给你在命令行里使用带来方便，Django自动生成的
    # admin里也使用这个方法来表示对象。
    def __str__(self):
        return self.gp_code


class Filling(models.Model):
    gp_code = models.CharField(max_length=32, default='000000', verbose_name='钢瓶编号')
    zn_code = models.CharField(max_length=32, default='WR23-', verbose_name='站内编号')
    factory = models.CharField(max_length=32, default='宣城百纳', verbose_name='制造厂商')
    sc_date = models.DateField(verbose_name='生产日期')
    jc_date = models.DateField(verbose_name='检测日期')
    weight = models.CharField(max_length=32, default='16kg', verbose_name='空瓶重量')
    checka = models.CharField(max_length=32, default='杜扬', verbose_name='充前检查员')
    fill_t = models.DateField(verbose_name='充装时间')
    process = models.CharField(max_length=32, default='正常')
    checkb = models.CharField(max_length=32, default='张伟伟', verbose_name='充装工')
    fillweight = models.CharField(max_length=32, default='29.5kg', verbose_name='满瓶重量')
    checkc = models.CharField(max_length=32, default='王光春', verbose_name='充后检查员')
    remark = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = '充装表'
    def __str__(self):
        return self.gp_code


class Record(models.Model):
    time = models.DateField('日期')
    gp_code = models.CharField(max_length=32, default='000000', verbose_name='钢瓶编号')
    client = models.CharField(max_length=64, verbose_name='客户名称')
    tel = models.CharField(max_length=32, verbose_name='预存电话')
    address = models.CharField(max_length=64, default='陵阳镇', verbose_name='使用地址')
    # DELIVERY_CHOICES = (
    #     ('1', '自取'),
    #     ('2', '杜扬'),
    #     (),
    #     (),
    # )
    # delivery = models.CharField(max_length=32, choices=DELIVERY_CHOICES, verbose_name='配送员')
    delivery = models.CharField(max_length=32, default='站点自取', verbose_name='配送员')
    remark = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = '收发记录表'
    def __str__(self):
        return self.gp_code

cylinders/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, get_list_or_404,render
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from . import models
from .templates import cylinders


def lookupBygp(request, gp_code):
    contents = {}
    try: 
        gpinfo = get_list_or_404(models.Gp, gp_code=gp_code)[-1] # 获取最新的一条
        contents.update({'gpinfo':gpinfo})
        czinfo = get_list_or_404(models.Filling, gp_code=gp_code)[-1]
        contents.update({'czinfo':czinfo})
        psinfo = get_list_or_404(models.Record, gp_code=gp_code)[-1]
        contents.update({'psinfo':psinfo})
    except:
        pass
    finally:
        return render(request, 'cylinders/gpinfo.html', contents)

def index(request):
    # try:
    #     gpinfo = models.Gps.objects.get(pk=1)
    # except models.Gps.DoesNotExist:
    #     raise Http404("Gps does not exist")
    # 还可以使用如下函数，不错
    try:
        gpinfo = get_object_or_404(models.Gp, pk=1)
    except:
        pass
    return render(request, 'cylinders/index.html', {'gpinfo': gpinfo})

def page1_gp(request):
    return render(request, 'cylinders/page1_gp.html')

def addGp(request):
    if request.method == 'POST':
        jf_code = request.POST['jf_code']
        gp_code = request.POST['gp_code']
        zn_code = request.POST['zn_code']
        sc_date = request.POST['sc_date']
        jc_date = request.POST['jc_date']
        manufacturer = request.POST['manufacturer']
        specification = request.POST['specification']
        company = request.POST['company']
        xj_date = request.POST['xj_date']
        bf_date = request.POST['bf_date']
        gp = models.Gp(jf_code=jf_code, gp_code=gp_code, zn_code=zn_code, 
                        sc_date=sc_date, jc_date=jc_date, 
                        manufacturer=manufacturer, specification=specification, 
                        company=company, xj_date=xj_date, bf_date=bf_date)
        gp.save()
    return HttpResponseRedirect(reverse('cylinders:page1_gp'))

cylinders/templates/cylinders/gpinfo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
<style type="text/css">
    .container{
        width: 540px;
        -webkit-box-pack: center;
        justify-content: center;
        margin: 0px auto;
    }
    .title{
        font-size:24px;
        margin: 0 auto;
    }
    .head{
        background-size: 100% 100%;
        text-align: center;
        background: #fff;
        padding-bottom: 10px;
    }
    .corp-name{
        font-size: 15px;
        color: #0F81EF;
        padding: 0 30px;
        font-weight: 600;
    }
    .container .row{
        background: #fff;
        margin-top: 8px;
        padding:10px 15px;
    }
    .time-line{
        display: flex;
        -webkit-box-pack: center;
        justify-content: center;
        height: 128px;
    }
    .time-line .item{
        position: relative;
        width: 100%;
        flex-direction: column;
    }
    .item .name{
        margin: 0 auto;
        width: 100%;
        font-size: 14px;
        margin-top: 25px;
        color: #666666;
    }
    .item>span{
        display: block;
        text-align: center;
    }

    .container .row{
        background: #fff;
        margin-top: 8px;
        padding:10px 15px;
    }
    .cylinder-detail{
        padding-top:15px !important;
    }
    .cylinder-detail .title{
        color: #333;
        text-align: center;
    }

    .cylinder-detail table{
        width: 100%;
    }
    .detail-table .opt{
        width: 40%;
        text-align: right;
        color: #666;
    }
    .detail-table .val{
        padding-left: 10px;
        text-align: left;
        color: #666;
    }
    body{
        max-width: 540px;
        margin:0 auto;
        background: #EFEFF4;
    }
    .copyright{
        padding: 8px 0;
        font-size: 14px;
        color:#666;
        text-align: center;
    }
    .time-line .item::before{
        content: '';
        position:absolute;
        top:45%;
        width: 45%;
        border-top:2px solid #0f81ef;
        z-index: 8;
    }
    .time-line .item::after{
        content: '';
        position: absolute;
        top: 40%;
        left: 50%;
        margin-left: -8px;
        width: 8px;
        height: 8px;
        border: 4px solid #0F81EF;
        background: #fff;
        border-radius: 50%;
        z-index: 9;
    }

    
</style>
</head>
<body>
    <div class="container">
        
        <!-- 钢瓶档案 -->
        <div class="row cylinder-detail">
            <p class="title">钢瓶档案</p>
            <table class="detail-table">
                <tbody>
                   
                    <tr>
                        <td class="opt">阀门编码：</td>
                        <td class="val" id="jf_code">{{ gpinfo.jf_code }}</td>
                    </tr>
                    <tr>
                        <td class="opt">钢瓶编号：</td>
                        <td class="val" id="gp_code">{{ gpinfo.gp_code }}</td>
                    </tr>
                    <tr>
                        <td class="opt">站内编号：</td>
                        <td class="val" id="zn_code">{{ gpinfo.zn_code }}</td>
                    </tr>
                    <tr>
                        <td class="opt">生产日期：</td>
                        <td class="val" id="sc_date">{{ gpinfo.sc_date }}</td>
                    </tr>
                    <tr>
                        <td class="opt">检测日期：</td>
                        <td class="val" id="jc_date">{{ gpinfo.jc_date }}</td>
                    </tr>
                    <tr>
                        <td class="opt">制造厂商：</td>
                        <td class="val" id="manufacturer">{{ gpinfo.manufacturer }}</td>
                    </tr>
                    <tr>
                        <td class="opt">型号规格：</td>
                        <td class="val" id="specification">{{ gpinfo.specification }}</td>
                    </tr>
                    <tr>
                        <td class="opt">充装单位：</td>
                        <td class="val" id="company">{{ gpinfo.company }}</td>
                    </tr>
                    <tr>
                        <td class="opt">下检日期：</td>
                        <td class="val" id="xj_date">{{ gpinfo.xj_date }}</td>
                    </tr>
                    <tr>
                        <td class="opt">报废日期：</td>
                        <td class="val" id="bf_date">{{ gpinfo.bf_date }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- 充装信息 -->
        <div class="row cylinder-detail">
            <p class="title">充装信息</p>
            <table class="detail-table">
                <tbody>
                    <tr>
                        <td class="opt">充装介质：</td>
                        <td class="val">液化石油气</td>
                    </tr>
                    <tr>
                        <td class="opt">最后一次充装时间：</td>
                        <td class="val" id="zhczsj">{{ czinfo.fill_t }}</td>
                    </tr>
                    <tr>
                        <td class="opt">操作员：</td>
                        <td class="val">{{ czinfo.checkb }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <!-- 配送信息 -->
        <div class="row cylinder-detail">
            <p class="title">配送信息</p>
            <br>
            <table class="detail-table">
                <tbody>
                    <tr>
                        <td class="opt">客户名称：</td>
                        <td class="val" id="csName">{{ psinfo.client }}</td>
                    </tr>
                    <tr>
                        <td class="opt">预留电话：</td>
                        <td class="val" id="csTel">{{ psinfo.tel }}</td>
                    </tr>
                    <tr>
                        <td class="opt">使用地址：</td>
                        <td class="val" id="csLocal">{{ psinfo.address }}</td>
                    </tr>
                    <tr>
                        <td class="opt">配送员工：</td>
                        <td class="val" id="sendName">{{ psinfo.delivery }}</td>
                    </tr>
                    <tr>
                        <td class="opt">送达时间：</td>
                        <td class="val" id="sendTime">{{ psinfo.time }}</td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="row cylinder-detail">
            {% load static %}
            <div style="text-align: center; width: 540px;">
                <img alt="" src="{% static 'cylinders/kefu.png' %}" style="margin: 0 auto;" />
                <p class="opt">24小时客服：18356257898/15956625731</p>
            </div>
        </div>

        <div class="row cylinder-detail">
            <p class="copyright">copyright @ 青阳县青山液化气站</p>
        </div>
    </div>
</body>
</html>

cylinders/templates/cylinders/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>hello cylinders</h1>
    
    <h1>{{ gpinfo.sc_date }}</h1>
    <h1></h1>
</body>
</html>

cylinders/templates/cylinders/page1_gp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>钢瓶信息录入页面</title>
    <style>
        #header {
            background-color:rgb(3, 78, 3);
            color:white;
            text-align:center;
            padding:5px;
        }
        #nav {
            line-height:30px;
            background-color:#eeeeee;
            height:500px;
            width:200px;
            float:left;
            padding:5px;
        }
        #section {
            width:350px;
            float:left;
            padding:10px;
        }
        #footer {
            background-color:rgb(3, 78, 3);
            color:white;
            clear:both;
            text-align:center;
            padding:15px;
        }
    </style>
</head>

<body>
    <div id='header'>
        <h1>钢瓶信息录入</h1>
    </div>

    <div id='nav'>
    <a href = "/">1-返回首页</a>
    <br><br>
    <a href = "/page3_kh">2-客户信息登记</a>
    <br><br>
    <a href = "/page2_gpquery">3-充装信息查询</a>
    <br><br>
    <a href = '/logout'>4-退出当前用户</a>
 
    </div>

    <div class="section">
        <table>
            <tr>
                <td>
                    <h3>钢瓶档案基本信息</h3>
                    <form action="{% url 'cylinders:addGp' %}" method="POST" name="addGp">
                        {% csrf_token %}
                        <p>角阀编号：<input type="text" name="jf_code"></p>
                        <p>钢瓶编号：<input type="text" name="gp_code"></p>
                        <p>站内编号：<input type="text" name="zn_code"></p>
                        <p>生产日期：<input type="text" name="sc_date"></p>
                        <p>检验日期：<input type="text" name="jc_date"></p>
                        <p>生产厂家：<input type="text" name="manufacturer", value="宣城百纳"></p>
                        <p>钢瓶规格：<input type="text" name="specification" value="YSP35.5"></p>
                        <p>充装单位：<input type="text" name="company" value="青山液化气站"></p>
                        <p>下检日期：<input type="text" name="xj_date"></p>
                        <p>报废日期：<input type="text" name="bf_date"></p>
                        <input type="submit" value="添加钢瓶档案">
                    </form>
                </td>
            </tr>
        </table>
    </div>

    <div id="footer">
        Copyright @ 青阳县青山液化气站
    </div>

</body>
</html>